"""streams_main

Revision ID: f046448948ec
Revises: 
Create Date: 2026-04-01 11:34:08.166516+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f046448948ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('entity_id_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_topics',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=255), nullable=True),
    sa.Column('triggers', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_youtube', sa.Boolean(), nullable=False),
    sa.Column('is_twitch', sa.Boolean(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('is_night', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('entity_id_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('entity_id_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_tg_id'), 'subscribers', ['tg_id'], unique=True)
    op.create_table('subscriber_stream_topics',
    sa.Column('subscriber_id', sa.BigInteger(), nullable=False),
    sa.Column('stream_topic_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stream_topic_id'], ['stream_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscriber_id', 'stream_topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriber_stream_topics')
    op.drop_index(op.f('ix_subscribers_tg_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_table('stream_topics')
    op.drop_table('configs')
    # ### end Alembic commands ###
